config/routes.rb
Rails.application.routes.draw do
  root 'admin/tickets#index'

  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_for :admins, controllers: { sessions: 'admin/sessions'}

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :tickets, only: [:index, :show, :create]
      resources :ticket_messages, only: :create
    end
  end

  namespace :admin do
    root to: redirect('/admin/tickets', status: 302)

    resources :tickets, only: [:index, :show, :edit, :update] do
      post 'claim', to: 'ticket_claims#create'
      resources :ticket_messages, only: :create
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :validatable

  has_many :tickets
  has_many :ticket_messages

  before_save :ensure_authentication_token

  def ensure_authentication_token
    if authentication_token.blank?
      self.authentication_token = generate_authentication_token
    end
  end

private

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(authentication_token: token).first
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  include ActiveModel::Serialization

  belongs_to :user
  belongs_to :admin, optional: true

  has_many :ticket_messages

  scope :unclaimed, -> { where(admin: nil) }
  scope :closed,    -> { where(closed: true) }

  def unclaimed?
    admin.blank?
  end

  def switch_closed_status
    self.closed = !closed
    self.save
  end
end

app/models/ticket_message.rb
class TicketMessage < ApplicationRecord
  include ActiveModel::Serialization

  belongs_to :ticket
  belongs_to :user, optional: true
  belongs_to :admin, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tickets
  has_many :ticket_messages

  before_save :ensure_authentication_token

  def ensure_authentication_token
    if authentication_token.blank?
      self.authentication_token = generate_authentication_token
    end
  end

private

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(authentication_token: token).first
    end
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_admin!

  layout "admin"
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Devise::SessionsController

protected
  def after_sign_in_path_for(resource)
    admin_tickets_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
end

app/controllers/admin/ticket_claims_controller.rb
class Admin::TicketClaimsController < Admin::BaseController

  def create
    ticket = Ticket.find(params[:ticket_id])

    if ticket.update_attributes(admin: current_admin)
      redirect_to admin_ticket_path(ticket)
    else
      redirect_to admin_tickets_path
    end
  end

end

app/controllers/admin/ticket_messages_controller.rb
class Admin::TicketMessagesController < Admin::BaseController
  def create
    current_ticket = current_admin.tickets.find(params[:ticket_id])
    ticket_message = current_admin.ticket_messages.build(message_params)
    ticket_message.ticket = current_ticket

    if ticket_message.save
      redirect_to admin_ticket_path(current_ticket)
    else
      redirect_to edit_admin_ticket_path(admin_ticket)
    end
  end

protected
  def message_params
    params.require(:ticket_message).permit(:content)
  end
end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < Admin::BaseController
  before_action :set_claimed_ticket, only: [:edit, :update]

  def index
    @unclaimed_tickets = Ticket.unclaimed
    @my_tickets = current_admin.tickets

    respond_to do |format|
      format.html
      format.pdf do
        render :pdf         => "file_name",
               :template    => 'admin/tickets/index.pdf.erb',
               :page_size   => "A4",
               :encoding    =>  'utf-8'
        end
    end
  end

  def show
    @ticket = Ticket.find(params[:id])
    @ticket_message = @ticket.ticket_messages.build
  end

  def edit
    @ticket_message = @ticket.ticket_messages.build
  end

  def update
    if @ticket.switch_closed_status
      redirect_to admin_tickets_path, notice: "The ticket has been updated"
    else
      render :edit
    end
  end

protected
  def set_claimed_ticket
    @ticket = current_admin.tickets.find(params[:id])
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  include ActionController::Serialization

  before_action :authenticate_user_from_token!
  before_action :authenticate_user!

  private

  def authenticate_user_from_token!
    authenticate_with_http_token do |token, options|
      user_email = options[:email].presence
      user = user_email && User.find_by_email(user_email)

      if user && Devise.secure_compare(user.authentication_token, token)
        sign_in user, store: false
      end
    end
  end
end

app/controllers/api/v1/ticket_messages_controller.rb
class Api::V1::TicketMessagesController < Api::V1::BaseController
  def create
    ticket_message = current_user.ticket_messages.build(message_params)

    if ticket_message.save
      render json: ticket_message
    else
      render json: ticket_message, status: :unprocessable_entity
    end
  end

protected
  def message_params
    params.require(:ticket_message).permit(:ticket_id, :content)
  end
end

app/controllers/api/v1/tickets_controller.rb
class Api::V1::TicketsController < Api::V1::BaseController
  def index
    render json: current_user.tickets, status: :ok
  end

  def show
    @ticket = current_user.tickets.find(params[:id])
    render json: @ticket
  end

  def create
    ticket = current_user.tickets.build(ticket_params)

    if ticket.save
      render json: ticket, status: :ok
    else
      render json: { errors: ticket.errors.full_messages }, status: :unprocessable_entity
    end
  end

protected
  def ticket_params
    params.require(:ticket).permit(:subject, :content)
  end
end

app/controllers/api/v1/users/base_controller.rb
class Api::V1::Users::BaseController < ApplicationController
  before_filter :authenticate_user_from_token!
  before_filter :authenticate_user!

  private

  def authenticate_user_from_token!
    authenticate_with_http_token do |token, options|
      user_email = options[:email].presence
      user = user_email && User.find_by_email(user_email)

      if user && Devise.secure_compare(user.authentication_token, token)
        sign_in user, store: false
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session, unless: -> { request.format.json? }
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  respond_to :html, :json

  def create
    super do |user|
      if request.format.json?
        data = {
          token: user.authentication_token,
          email: user.email
        }
        render json: data, status: 201 and return
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def switch_status(ticket)
    ticket.closed? ? 'Re-Open Ticket' : 'Close Ticket'
  end

  def status_label(ticket)
    ticket.closed? ? 'Closed' : 'Open'
  end

  def status_class(ticket)
    ticket.closed? ? 'btn btn-danger' : 'btn btn-info'
  end
end

app/views/admin/tickets/_list.erb
<div class="row">
  <div class=".col-sm-12.col-md-12">
    <div class="block-flat">
      <div class="content">
        <%- if tickets.any? %>
          <table class="no-border">
            <thead class='no-border'>
              <tr>
                <th>Subject</th>
                <th>Date and time</th>
                <th></th>
              </tr>
            </thead>
            <tbody class=' no-border-x no-border-y'>
              <% tickets.each do |ticket| %>
                <tr data-ticket="<%= ticket.id %>" class="js--tr-clickeable">
                  <td>
                    <%= ticket.subject %>
                  </td>
                  <td>
                    <%= ticket.created_at.strftime("%m.%d.%y at %l:%M %p") %>
                  </td>
                  <% if ticket.unclaimed? %>
                    <td>
                      <%= link_to 'Claim', admin_ticket_claim_path(ticket), method: :post, class: "btn btn-primary"  %>
                      <%= link_to 'View', admin_ticket_path(ticket), class: "btn btn-info" %>
                    </td>
                  <% else %>
                    <td>
                      <%= link_to 'Respond', admin_ticket_path(ticket), class: "btn btn-primary" %>
                      <a href="#" class="<%= status_class(ticket) %>"><%= status_label(ticket) %></a>
                      </td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
        <%- else %>
          <div class="alert alert-info">
            <i class="fa fa-info-circle sign"></i>
            <strong>There aren't tickets</strong>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/tickets/edit.html.erb
<div class="row">
  <div class="col-sm-12 col-md-12">
    <div class="spacer spacer-bottom">
      <%= link_to switch_status(@ticket), admin_ticket_path(@ticket), method: :put, class: 'btn btn-block btn-primary btn-rad' %>
    </div>
    <div class="message">
      <div class="head">
        <h3>Subject:  <%= @ticket.subject %></h3>
        <span><%= @ticket.created_at.strftime("%m/%d/%Y - %I:%M%p") %></span>
      </div>
      <div class="mail">
        <p><%= @ticket.content %></p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class=" col-sm-12 col-md-12">
    <h2>Messages</h2>
  </div>
</div>

<div class="row">
  <div class="col-sm-12 col-md-12">
    <%- if @ticket.ticket_messages.size > 1 %>
      <% @ticket.ticket_messages.each do |message| %>
        <div class="message">
          <div class="mail">
            <p><%= message.content %></p>
          </div>
        </div>
      <% end %>
    <%- else %>
      <div class="alert alert-info">
        <i class="fa fa-info-circle sign"></i>
        <strong>There aren't answers</strong>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-sm-12 col-md-12">
    <%= form_for @ticket_message, url: admin_ticket_ticket_messages_path(@ticket) do |f| %>
      <div class="wrapper">
        <% if @ticket_message.errors.any? %>
          <div>
            <div>
              <%= pluralize(@ticket_message.errors.count, "error") %> prohibited this audit from being saved:
            </div>
            <div>
              <ul>
                <% @ticket_message.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>

        <div class=".form-group">
          <%= f.label :content, "Comments" %>
          <%= f.text_area :content, class: "form-control", size: "30x10" %>
        </div>

        <%= f.submit "Create Ticket message", class: "btn btn-info margin-top-30" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/tickets/index.html.erb
<div class="row">
  <div class="col-sm-12 col-md-12">
    <p id="notice">
      <%= notice %>
    </p>
  </div>
</div>

<div class="row">
  <div class="col-sm-12 col-md-12">
    <h2>Unclaimed Tickets</h2>
  </div>
</div>

<%= render 'list', tickets: @unclaimed_tickets %>

<div class="row">
  <div class="col-sm-12 col-md-12">
    <h2>My Tickets</h2>
  </div>
</div>

<%= render 'list', tickets: @my_tickets %>

app/views/admin/tickets/index.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
  </head>
  <body onload='number_pages'>
     
    <div class="row">
      <h1>Pending tickets</h1>
    </div>

    <div class="row">
      <table>
        <thead>
          <tr>
            <th>Subject</th>
            <th>User</th>
            <th>Date and time</th>
          </tr>
        </thead>
        <tbody>
          <% Ticket.all.each do |ticket| %>
            <tr data-insight="<%= ticket.id %>" class="js--tr-clickeable">
              <td>
                <%= ticket.subject %>
              </td>
              <td>
                <%= ticket.user.email %>
              </td>
              <td>
                <%= ticket.created_at.strftime("%m.%d.%y at %l:%M %p") %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </body>
</html>

app/views/admin/tickets/show.html.erb
<div class="row">
  <div class="col-sm-12 col-md-12">
    <div class="message">
      <div class="head">
        <h3>Subject:  <%= @ticket.subject %></h3>
        <span><%= @ticket.created_at.strftime("%m/%d/%Y - %I:%M%p") %></span>
      </div>
      <div class="mail">
        <p><%= @ticket.content %></p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class=" col-sm-12 col-md-12">
    <h2>Messages</h2>
  </div>
</div>

<div class="row">
  <div class="col-sm-12 col-md-12">
    <%- if @ticket.ticket_messages.size > 1 %>
      <% @ticket.ticket_messages.each do |message| %>
        <div class="message">
          <div class="mail">
            <p><%= message.content %></p>
          </div>
        </div>
      <% end %>
    <%- else %>
      <div class="alert alert-info">
        <i class="fa fa-info-circle sign"></i>
        <strong>There aren't answers</strong>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-sm-12 col-md-12">
    <%= form_for @ticket_message, url: admin_ticket_ticket_messages_path(@ticket) do |f| %>
      <div class="wrapper">
        <% if @ticket_message.errors.any? %>
          <div>
            <div>
              <%= pluralize(@ticket_message.errors.count, "error") %> prohibited this audit from being saved:
            </div>
            <div>
              <ul>
                <% @ticket_message.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>

        <div class=".form-group">
          <%= f.label :content, "Comments" %>
          <%= f.text_area :content, class: "form-control", size: "30x10" %>
        </div>

        <%= f.submit "Create Ticket message", class: "btn btn-primary margin-top-30" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TickrApi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container-fluid">

      <div id="head-nav" class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-collapse">
            <ul class="nav navbar-nav navbar-right user-nav">
              <li class="dropdown profile_menu">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" > </a>
                  <span>
                    <%= link_to 'Logout', destroy_admin_session_path, :method => :delete %>
                  </span>
              </li>
            </ul>

            <ul class="nav navbar-nav not-nav">
              <li class="profile_menu">
                <%= link_to 'Tickets', admin_tickets_path, class: "toggle-menu menu-right push-body" %>
              </li>
              <li class="profile_menu">
                <%= link_to "PDF Report", admin_tickets_path(format: :pdf), class: "toggle-menu menu-right push-body" %>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <div class="cl-mcont">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TickrApi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>